#ifndef ATLSVM

#define ATLSVM_FCODE_LST \
	ATLSVM_DEF(ATLSVM_ADD,   2, ATLSVM_BINOP(+)) \
	ATLSVM_DEF(ATLSVM_SUB,   2, ATLSVM_BINOP(-)) \
	ATLSVM_DEF(ATLSVM_MUL,   2, ATLSVM_BINOP(*)) \
	ATLSVM_DEF(ATLSVM_DIV,   2, ATLSVM_BINOP(/)) \
	ATLSVM_DEF(ATLSVM_MOD,   2, ATLSVM_FN2(fmod)) \
	ATLSVM_DEF(ATLSVM_NEG,   1, ATLSVM_UNOP(-)) \
	\
	ATLSVM_DEF(ATLSVM_NOT,   1, ATLSVM_UNOP(!)) \
	ATLSVM_DEF(ATLSVM_EQ,    2, ATLSVM_BINOP(==)) \
	ATLSVM_DEF(ATLSVM_NEQ,   2, ATLSVM_BINOP(!=)) \
	ATLSVM_DEF(ATLSVM_LT,    2, ATLSVM_BINOP(<)) \
	ATLSVM_DEF(ATLSVM_LE,    2, ATLSVM_BINOP(<=)) \
	ATLSVM_DEF(ATLSVM_GT,    2, ATLSVM_BINOP(>)) \
	ATLSVM_DEF(ATLSVM_GE,    2, ATLSVM_BINOP(>=)) \
	ATLSVM_DEF(ATLSVM_AND,   2, ATLSVM_BINOP(&&)) \
	ATLSVM_DEF(ATLSVM_OR,    2, ATLSVM_BINOP(||)) \
	\
	ATLSVM_DEF(ATLSVM_SIN,   1, ATLSVM_FN1(sinf)) \
	ATLSVM_DEF(ATLSVM_COS,   1, ATLSVM_FN1(cosf)) \
	ATLSVM_DEF(ATLSVM_ATAN,  1, ATLSVM_FN1(atanf)) \
	ATLSVM_DEF(ATLSVM_SQRT,  1, ATLSVM_FN1(sqrtf)) \
	ATLSVM_DEF(ATLSVM_EXP,   1, ATLSVM_FN1(expf)) \
	ATLSVM_DEF(ATLSVM_POW,   2, ATLSVM_FN2(powf)) \
	\
	ATLSVM_DEF(ATLSVM_FLOOR, 1, ATLSVM_FN1(floorf)) \
	ATLSVM_DEF(ATLSVM_CEIL,  1, ATLSVM_FN1(ceilf)) \
	ATLSVM_DEF(ATLSVM_ROUND, 1, ATLSVM_FN1(roundf)) \
	\
	ATLSVM_DEF(ATLSVM_LERP,  3, ATLSVM_FN3(fcf_lerp))

enum atlsvm_fcode {
	ATLSVM__ZERO = 0,

	#define ATLSVM_DEF(t,n,fn) t,
	ATLSVM_FCODE_LST
	#undef ATLSVM_DEF

	ATLSVM__MAX
};

static inline char* atlsvm_fcode_str(enum atlsvm_fcode fc)
{
	switch (fc) {
	#define ATLSVM_DEF(t,n,fn) case t: return #t;
	ATLSVM_FCODE_LST
	#undef ATLSVM_DEF
	default:
		return "????";
	}
}


#define ATLSVM
#endif
