CFLAGS+=-O0 -g
#CFLAGS+=-Os -g
#CFLAGS+=-O3
#CFLAGS+=-Os
CFLAGS+=-Wall

all: $(ARTIFACT)

#OBJS+=do.o # application

OBJS+=stb_ds.o editor_client.o utf8.o
OBJS+=stb_truetype.o stb_rect_pack.o stb_image_resize2.o stb_image_write.o
OBJS+=font0.o sep2dconv.o gui.o

LDFLAGS+=-lm

$(ARTIFACT): $(OBJS)
	$(CC) -o $(ARTIFACT) $(OBJS) $(LDFLAGS)

clean:
	rm -f *.o *.wasm $(ARTIFACT)
