#CFLAGS+=-O0 -g
CFLAGS+=-Os -g
CFLAGS+=-Wall

all: $(ARTIFACT)

#OBJS+=do.o # application

OBJS+=frontend_windowed.o editor_client.o utf8.o stb_truetype.o stb_rect_pack.o font0.o
OBJS+=stb_image_resize2.o

LDFLAGS+=-lm

$(ARTIFACT): $(OBJS)
	$(CC) -o $(ARTIFACT) $(OBJS) $(LDFLAGS)

clean:
	rm -f *.o *.wasm $(ARTIFACT)
